name: ornek_deneme_calisma
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  collapsible_sidebar: ^2.0.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  fluttericon: ^2.0.0
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  flutter_dotenv: ^5.0.2

  dropdown_button2: ^1.8.5
  shared_preferences: ^2.0.15

  flutter_native_splash: ^2.2.14
  flutter_map: ^3.0.0
  maps_launcher: ^2.0.1
  url_launcher: 6.0.18

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/dovizLogo-light-theme.png
    - assets/images/dovizLogo-dark-theme.png
    - assets/images/ozak-light-theme.png
    - assets/images/ozak-dark-theme.png
    - assets/images/sarrafiyeLogo-light-theme.png
    - assets/images/sarrafiyeLogo-dark-theme.png
 
    - assets/images/location.png
    - assets/images/moon.png
    - assets/images/remove.png
    - assets/images/menu-light-theme.png
    - assets/images/menu-dark-theme.png
    - assets/images/footerfoto.png
    - assets/images/currency_and_mine_icons/AED.png
    - assets/images/currency_and_mine_icons/AUD.png
    - assets/images/currency_and_mine_icons/BGN.png
    - assets/images/currency_and_mine_icons/CAD.png
    - assets/images/currency_and_mine_icons/CHF.png
    - assets/images/currency_and_mine_icons/CNY.png
    - assets/images/currency_and_mine_icons/DKK.png
    - assets/images/currency_and_mine_icons/EUR.png
    - assets/images/currency_and_mine_icons/GBP.png
    - assets/images/currency_and_mine_icons/GUM.png
    - assets/images/currency_and_mine_icons/HAS.png
    - assets/images/currency_and_mine_icons/JOD.png
    - assets/images/currency_and_mine_icons/JPY.png
    - assets/images/currency_and_mine_icons/KG.png
    - assets/images/currency_and_mine_icons/Kulce.png
    - assets/images/currency_and_mine_icons/KWD.png
    - assets/images/currency_and_mine_icons/MAD.png
    - assets/images/currency_and_mine_icons/NOK.png
    - assets/images/currency_and_mine_icons/OMR.png
    - assets/images/currency_and_mine_icons/QAR.png
    - assets/images/currency_and_mine_icons/RUB.png
    - assets/images/currency_and_mine_icons/SAR.png
    - assets/images/currency_and_mine_icons/SEK.png
    - assets/images/currency_and_mine_icons/TRY.png
    - assets/images/currency_and_mine_icons/USD.png
    - assets/images/currency_and_mine_icons/XAG.png
    - assets/images/currency_and_mine_icons/XAU.png
    - assets/images/down_icon.png
    - assets/images/up_icon.png
    - assets/images/applestore.png
    - assets/images/call.png
    - assets/images/facebook.png
    - assets/images/instagram.png
    - assets/images/map.png
    - assets/images/mockup-scene.png
    - assets/images/playstore.png
    - assets/images/sms.png
    - assets/images/twitter.png
    - assets/images/youtube.png
    - assets/images/moon.png
    - assets/images/sun.png







  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Euclid-Circular-B
      fonts:
        - asset: assets/fonts/Euclid-Circular-B-Medium.ttf




  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
